In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(np.__version__)

1.24.3


In [5]:
print(arr.ndim)
# to get the dimensions of array

1


In [6]:
new=np.array([1,2,3,4],ndmin=5)
new

array([[[[[1, 2, 3, 4]]]]])

In [11]:
print(new.ndim)

5


In [12]:
arr[0]

1

In [13]:
arr[0]+arr[2]

4

In [16]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1[0,1]

2

In [17]:
arr[:2]

array([1, 2])

In [19]:
print(arr[:5])

[1 2 3 4 5]


In [27]:
print(arr[1:5])
# in this case 1st index from start to 5th index from start where 5th index got ignored

[2 3 4 5]


In [21]:
print(arr[1:])

[2 3 4 5 6]


In [28]:
arr[-4:-1]
# in reverse slicing 4th index from end (2) to first index from end where -4th index got ignored
# in forward slicing ending index and in backward slicing starting index goes ignored

array([3, 4, 5])

In [29]:
arr

array([1, 2, 3, 4, 5, 6])

In [30]:
arr[1:5:2]

array([2, 4])

In [31]:
arr[::2]

array([1, 3, 5])

In [32]:
arr1[1,0:]

array([4, 5, 6])

In [33]:
arr1[1,0:1]

array([4])

In [35]:
arr1[0:,1]

array([2, 5])

In [37]:
arr1[0:,1:]

array([[2, 3],
       [5, 6]])

In [39]:
print(arr.dtype)

int64


In [40]:
s=np.array(['a','b'])
s

array(['a', 'b'], dtype='<U1')

In [41]:
s.dtype
# OP: U1 : where U is unicode string and 1 means 1 character size

dtype('<U1')

In [46]:
arr2=np.array([1,2,3,4],dtype='S')

In [47]:
arr2

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [48]:
arr3=np.array([1,2,3,4],dtype='i4')

In [49]:
arr3

array([1, 2, 3, 4], dtype=int32)

In [56]:
arr4=np.array(['1','a'],dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [62]:
new2=np.array([1.1,1.2,1.4])
print(new2)
print(new2.dtype)

[1.1 1.2 1.4]
float64


In [63]:
new2=new2.astype('i')

In [64]:
new2

array([1, 1, 1], dtype=int32)

In [65]:
new3=np.array([1,2,3,4,5.1,1.78])
print(new3)
print(new3.dtype)

[1.   2.   3.   4.   5.1  1.78]
float64


In [66]:
new3=new3.astype(int)
new3

array([1, 2, 3, 4, 5, 1])

In [67]:
print(new3.dtype)

int64


In [73]:
new4=np.array([-1,1,0,0,3,4])
print(new4)

[-1  1  0  0  3  4]


In [74]:
new4=new4.astype(bool)

In [75]:
new4

array([ True,  True, False, False,  True,  True])